### PR TITLE
add storage support

### PR DESCRIPTION
**Pull request by abuibrahim**

### CODE REVIEW

**Comment by portnov** [comment]
Hello
For some reason during compilation i got

System/LibVirt/Foreign.chs:555:12: Not in scope: ‘<$>’

System/LibVirt/Foreign.chs:638:18: Not in scope: ‘<$>’

System/LibVirt/Foreign.chs:664:18: Not in scope: ‘<$>’

**Comment by portnov** [comment]
I suppose we have to import Control.Applicative in the beginning of Foreign.chs.

**Comment by abuibrahim** [comment]
Or we could just use fmap. I didn't get the errors BTW - using ghc-7.10.3.

Let me redo it and I'll send another PR.

**Comment by abuibrahim** [comment]
will send another PR

**Pull request closed without merging**
